// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Reflection;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Microsoft.Samples.Kinect.BackgroundRemovalBasics.model
{

    [Obfuscation(Feature = "trigger", Exclude = false)]
    public class CheckInUserMain
    {
        [JsonProperty("response_code")]
        public int ResponseCode { get; set; }
          
        [JsonProperty("user")]
        public User User { get; set; }
    }

}
