// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Reflection;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Microsoft.Samples.Kinect.BackgroundRemovalBasics.model
{

    [Obfuscation(Feature = "trigger", Exclude = false)]
    public class User
    {

        [JsonProperty("name")]
        public string Name { get; set; }


        [JsonProperty("avatar")]
        public string Avatar { get; set; }


        [JsonProperty("id")]
        public int? Id { get; set; }
         
    }

}
